- locust_plugins/transaction_manager.py
Fixes #30 and #32
Use the built-in `csv` module to ensure that error messages are properly encoded when they contain quotes, newlines, or commas.
Possibly breaking:
- `report_to_master` data key renamed from `flat_transaction_list` to `transactions` since the value no longer represents a flat list. It is now a list of lists.
Other changes:
- Add the `--log-transactions-in-file` argument to the existing `Request statistics options` argument group defined by Locust. Inserts the group if does not exist, i.e., if Locust core changes the group name the plugin will not fail.
> Use csv module for csv output

- locust_plugins/appinsights_listener.py
This PR addresses #41 
An additional, optional, parameter to the ApplicationInsights constructor allows the user to control whether the AI logger propagates events to the parent logger.
The default is that is does (i.e. that `propagate_logs` is `True`) to maintain backward compat. By setting this param to `False` the AI events continue to be handled by the `AzureLogHandler`, but are not then propagated to the parent logger and streamed to the console.
If you'd like me to add any examples/update docs, please let me know. 
Happy to help, and thank you for these locust plugins!
> Allow Control over Log Propagation to Parent Logger. Fixes #41

- locust_plugins/appinsights_listener.py
My previous PR tried to set `propagate_logs` as if it were a function. 
Not sure how I managed this, as my local test code set it as a property. 
Totally my fault.
> fix broken call to set propagate_logs

- locust_plugins/timescale_schema.sql
After step-by-step execution of points from [example](https://github.com/SvenskaSpel/locust-plugins/blob/master/examples/timescale_listener_ex.py) when launching load tests, an error occurred due to a broken table schema
> Fix missed columns in 'testrun' table schema (timescale_schema.sql)

- .gitignore
- locust_plugins/users/kafka.py
- locust_plugins/users/webdriver.py
Makes it possible to specify name and context to kafka user. Will also fire the new request event instead of old failure/success
> Updaes to kafka user

- locust_plugins/timescale_schema.sql
Sometimes when we're working with git repos inside a group the actual limit of 40 characters becomes small causing an insertion failure. It's normal when the company use `gitlab` and many subgroups of teams. Please consider this small change.
> resize timescaledb gitrepo testrun column.

- locust_plugins/transaction_manager.py
In an environment with the latest version of locust, transaction manager does not work, failing with the following message
```
File "/home/serhiy/.local/lib/python3.8/site-packages/locust_plugins/transaction_manager.py", line 165, in _transactions_results_page
headers["Content-disposition"] = f"attachment;filename={cls.transactions_filename}"
AttributeError: type object 'TransactionManager' has no attribute 'transactions_filename'
```
This PR should fix this
> Add missing declarations and parenthesis

- README.md
- examples/mqtt_ex.py
- locust_plugins/users/__init__.py
- locust_plugins/users/mqtt.py
- setup.py
This PR adds an MqttUser class for load testing MQTT clients.
The functionality is loosely based on the work from [concurrencylabs/mqtt-locust](https://github.com/concurrencylabs/mqtt-locust), which targets Python 2 & an older version of Locust.
The usage & design loosely follows that of the KafkaUser class: I found it similar enough to the MQTT use-case (connect to broker, publish messages) so the usage should be _fairly_ similar.
The easiest way to run the example is to:
- remove the TLS snippets
- target port 1883 instead of 8883
- start an MQTT broker on your local machine
- e.g., using the mosquitto Docker image:
`docker run -it -p 1883:1883 eclipse-mosquitto mosquitto -c /mosquitto-no-auth.conf`
> P.S. the CONTRIBUTING.md document mentioned creating an issue if you wanted to discuss …
> Add new User for MQTT

- examples/connection_pool_ex.py
- locust_plugins/connection_pools.py
- setup.py
Add connection pool object for HTTP user and fast HTTP user. 
Allows for a user class to occupy more ports. Particularly useful in low user high throughput situations  where a target load balancer may not behave as expected
> Connection pools

- .pylintrc
- examples/debug_ex_advanced.py
- examples/reschedule_on_fail_ex.py
- examples/rest_ex.py
- examples/socketio_ex.py
- examples/webdriver_ex.py
- locust_plugins/users/webdriver.py
- tox.ini
- tusk.yaml
Rename the webdriver client to prevent overloading the standard selenium find_element method.
Adds a context manager that handles errors, and firing of events to locust
Resolves https://github.com/SvenskaSpel/locust-plugins/issues/68
Example test run output
```
❯ PYTHONPATH=. python examples/webdriver_ex.py
type	name                                              	resp_ms	exception	
Webdriver	failure_with_context_manager2                     	5215   	Exception('Webdriver Exception:no such element: Unable to locate element: {"method":"css selector","selector":"body > div > div"}\n  (Session info: chrome=96.0.4664.93)')	
Webdriver	failure_with_context_manager                      	5629   	Exception('Timeout waiting for Webdriver:')	
Webdriver	failure_with_context_manager2 …
```
> Allow use of context manager with webdriver

- locust_plugins/dashboards/locust-timescale/timescale_schema.sql
This is actually failing your load test if your git remote url is longer than 40 characters
> gitrepo is too short to store most git repo

- README.md
- locust_plugins/connection_pools.py
Some Fixups from my last PR
- Fixes the broken example and source a broken link in readme.md
- RequestPool and FastRequestPool Now support the `with pool.rename_request()` syntax
- Adds two new classes, which create a new Request session and FastHTTPSession object for every request call. Forcing the host machine to use new ports
> ConnectionPools fixups

- .pylintrc
- locust_plugins/listeners.py
Updated logic for Timescale master and worker identification function. 
Added logic to sync run-id between master and worker. only in localrunner mode it works as well.
Tested below
- Ran a test in local runner
- Ran a test in master worker config
- Ran a test by giving run-id in config
> fixed run-id diff issue for timescale

- bin/locust-compose
- tox.ini
The script was modified to avoid related errors caused by the upgrade of docker-compose version. The specific issue is that, as mentioned in the [web page](https://docs.docker.com/compose/install/linux/), Compose V1 will no longer be supported.
> Timescale/Dashboards: Use docker compose v2 syntax

- locust_plugins/users/mqtt.py
Propagate return values of Paho's original `Client.publish` and `Client.subscribe` methods back to the caller of `MqttClient`. This allows writing code on `MqttUser` instances as if one was dealing with the original client, e.g.
```python
class MyUser(MqttUser):
@task
def report_battery_level(self):
msginfo = self.client.publish('reporting/battery', b'soc=99')
msginfo.wait_for_publish()
```
> Propagate return values of Paho's original client methods

- README.md
It was removed in https://github.com/SvenskaSpel/locust-plugins/pull/138, since it's `locust.debug.PrintListener` now.
------
Thanks for sharing all those plugins, it's a great resource 👏 🥳
> README.md: Remove Print

- examples/cloudwatch_listener_ex.py
- locust_plugins/listeners/cloudwatch.py
- setup.py
- test/test_cloudwatch_plugin.py
A plugin which will allow locust metrics (request count, response time etc.) to be pushed to AWS cloudwatch (using boto3)
> Cloudwatch plugin

- examples/mqtt_custom_client_ex.py
- locust_plugins/users/mqtt.py
Added this to allow the option for users to customize the events logged in the database.
This would be done by extending the `MqttClient` class and overriding the `_generate_event_name` method.
For example when sending messages on a large variety of topics this generates a very fuzzy and hard-to-read set of charts in Grafana.
A more generic, simple view may be required.
Altering the queries in the Grafana dashboards to simplify the charts can be error-prone, performance downgrading, and will create maintenance overhead.
This solution allows users to alter the logged entry in the database for a more use-case-centric grouping.
I can provide more details of required - like a very simple dataset.
Thank you
> allowing more extensibility to customize the mqtt events logged in the database

- setup.py
As suggested in https://github.com/SvenskaSpel/locust-plugins/issues/180#issuecomment-2191549079
> pin paho-mqtt dependency to >=2.1.0 to keep the old callback API version

- examples/mqtt_custom_client_ex.py
- examples/mqtt_ex.py
- locust_plugins/users/mqtt.py
Added different callback signatures in the `MqttClient` for
- on_connect
- on_disconnect
to support MQTT v5.0
As per the comments in the paho mqtt client:
```
"""The callback called when the broker reponds to our connection request.
Expected signature for callback API version 2::
connect_callback(client, userdata, connect_flags, reason_code, properties)
Expected signature for callback API version 1 change with MQTT protocol version:
* For MQTT v3.1 and v3.1.1 it's::
connect_callback(client, userdata, flags, rc)
* For MQTT v5.0 it's::
connect_callback(client, userdata, flags, reason_code, properties)
:param Client client: the client instance for this callback
:param userdata: the private user data as set in Client() or user_data_set()
:param ConnectFlags connect_flags: the flags for this …
```
> MQTT v5.0 support

- locust_plugins/users/mqtt.py
I introduced an issue in my PR yesterday.
The `MqttClient` does not have the `protocol` property.
It is passed as a parameter.
Sorry about this.
> MqttClient does not have the protocol property
